contentColumnType: string
fieldGroup: 07a123c0-4e8e-4c19-a79e-61829f5d88c0
handle: headerBuilder
instructions: ''
name: 'Header Builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_headerbuilder}}'
  maxBlocks: '1'
  minBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
