dateModified: 1639480290
email:
  fromEmail: $SYSTEM_EMAIL
  fromName: $SENDER_NAME
  replyToEmail: $REPLY_TO
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0dd08fc1-c043-49cb-bdcf-80521b7bd98a: Settings # Settings
    1aad5a2f-f77c-42d8-8c02-c97817b9cb18: 'The Answer' # The Answer
    1c23eb9d-03fe-46ea-9bee-ff46e8bd15a3: 'Teaser Image' # Teaser Image
    1d22d2ae-5175-4154-b830-51c806bfbf5b: 'Article Body' # Article Body
    1dd95078-7c8a-4ef7-8a16-e33a5341dadb: 'Image Optimisations ' # Image Optimisations 
    2c244265-381c-45ad-b439-7845b814e5ee: Resources # Resources
    2cfafcad-5b14-408b-ba81-afd942b8b3cb: 'Profile Images' # Profile Images
    2d711019-2880-4c21-8217-ff88e953e2bb: News # News
    3a030d4d-66bf-4bff-af6b-a3366b617b7e: 'Image Gallery' # Image Gallery
    3ef3485e-6187-4dac-af6b-66d630852b61: Quote # Quote
    3f37c536-3682-4856-a6af-a9f582d4c782: Style # Style
    3fc84cf5-6e3d-46e8-bf13-9a1d4e198438: Caption # Caption
    4a86f07d-200e-4dbc-a06a-223d9cc5c049: Images # Images
    4e026396-d7ab-43ef-a817-226fb2dada30: 'FAQ Categories' # FAQ Categories
    5c642d7e-b16b-4836-9575-668d75d242e5: Branding # Branding
    5da841b1-ca0d-46ff-8bb1-04d6c889ac54: Default # Default
    5ecf59f4-1339-4602-bd54-aa112f8f098e: Categories # Categories
    6a3feb81-50ce-467a-8aca-b5d4cc12aed0: Description # Description
    6c47b7b0-71d0-4acb-92d5-6d8624f711fb: Cards # Cards
    6d157457-cb17-4d30-b2cd-ade98a8fdcf0: 'Privacy Links' # Privacy Links
    6fcc732b-3375-496d-92b8-64f3dcc00d00: Heading # Heading
    07a123c0-4e8e-4c19-a79e-61829f5d88c0: Builders # Builders
    7b47dfe8-236f-43bb-8f44-17ed8a51b202: Developers # Developers
    8c97ba02-9121-4684-971f-b958193f7707: Standfirst # Standfirst
    9de367ab-77b8-47bb-bbc3-63e79a202c3e: News # News
    9e045942-6f83-412f-a36b-2110bc737ce7: 'Public Schema' # Public Schema
    9e682a2f-b0d4-478b-8b06-549c218b8357: 'FAQ List' # FAQ List
    11cffc84-a18e-49e3-9923-8229743b2a28: Branding # Branding
    13d83534-d33c-4c02-8e9a-8214c5419071: 'Landings Page' # Landings Page
    14e48735-7707-43d5-a6f1-90cc18da80f1: Teasers # Teasers
    17ffd720-73f0-4e0c-9878-ea089fcc6863: Sliders # Sliders
    21df72f8-6b89-4f91-9c09-d04a531f29de: Description # Description
    35a1d959-d78e-4445-891c-7bb671c48281: 'Optimize Teasers' # Optimize Teasers
    040d9f96-b22c-414c-8b92-9ec41f548a81: Description # Description
    46faf86d-bfa5-4356-bef1-0af3b2a87332: 'Secondary Navigation' # Secondary Navigation
    47b7409b-e345-48d9-b684-06ec0a2972f5: FAQ # FAQ
    47c98ad7-c9a9-402c-9171-9fd14eb7e8f4: 'Highlight Cards' # Highlight Cards
    49d732ef-0bfc-46c0-ba09-004de008c0ba: Ratio # Ratio
    54daa4d7-b5cf-4458-9e19-67155be19343: 'Organisation Phone' # Organisation Phone
    54e60257-f31a-44aa-960e-bbd364197e28: Homepage # Homepage
    58be0817-ea24-401b-98eb-4a60d7e7e34b: 'Content Page' # Content Page
    062e0067-ec18-423d-9e99-cce96beada4b: 'Optimize Covers' # Optimize Covers
    68e8bef5-3752-4c83-a67b-6fe5d31c976a: Button # Button
    74c703ba-fb2c-421f-9b09-2bd3762770de: 'Footer Navigation' # Footer Navigation
    75b2db97-9323-4a3f-9865-e3b6d2f3e785: 'Basic Slider' # Basic Slider
    85e4f238-143a-4f69-9291-c34e53b912ee: 'Hero Content' # Hero Content
    88bcc4ff-c9d0-4c32-9891-2d01044026a6: FAQ # FAQ
    94b4d5ac-d7ea-4241-a6cb-92b39f482f99: Common # Common
    302a5592-8085-472e-9356-ab6b1eaf1635: Position # Position
    0314e405-e731-462f-9381-2cfb6ac91134: Images # Images
    346cce90-1d6e-4c2d-82c0-c91b571c741c: 'Section Header' # Section Header
    451cb28a-2133-4681-977d-41c5a1cbc887: 'Full Logo' # Full Logo
    502c51a1-5b82-4368-90e1-aa68b1d4e479: 'Cover Photo' # Cover Photo
    634bebf5-ce96-4127-ab28-ee2541fb9f3b: 'Optimize Slider Images' # Optimize Slider Images
    648e7555-63ed-4228-a6b7-7811c865a7af: 'Category Description' # Category Description
    712cce4e-490d-44b8-bf2c-5d00c2de4c40: Assets # Assets
    0827c9dd-2ea2-4e98-b743-3161e028a304: 'FAQ Category' # FAQ Category
    870c07d7-9341-4f1f-825b-25c76239bc0d: Caption # Caption
    918b50e1-632c-4e92-a8c5-55eeb7b8571e: 'Cover Photos' # Cover Photos
    1105c63e-3aaf-403a-8259-736f0a2d47f8: Heroes # Heroes
    1266c39b-94f2-433c-ac8e-e84aa225a740: 'Header Builder' # Header Builder
    1572f461-2a67-47a4-a36c-80839168bcb7: Globals # Globals
    2473fef2-babd-4336-bb2e-550dc284282c: FAQ # FAQ
    4133e37a-d625-476e-91aa-a600e0123064: 'Quote Source' # Quote Source
    4285cde2-58a1-4cde-aba3-ccdced328ee2: Button # Button
    4697a491-b07d-46f9-87d8-c6cd9fb804a9: Target # Target
    5053ff27-8e1b-49ea-85c6-c2a1dece3b8e: 'Body Content' # Body Content
    6843ef52-9bcd-483a-956a-b63193181c85: Heading # Heading
    6962a9b1-b802-4295-82b1-398470a9f54c: Author # Author
    9806bc10-174e-4280-b2a8-c684b99a3139: 'Optimize Profile Images' # Optimize Profile Images
    11916eb5-92ff-4945-bb06-1406d6047b36: 'Slider Image Placeholder' # Slider Image Placeholder
    25958ba0-5f4a-48fc-9dee-0064db99f702: 'Utility Icon' # Utility Icon
    35981b2e-d04e-4366-939a-c0673263711a: Questions # Questions
    37051ce6-f0ea-4d54-97a5-e8c0f304f99c: Type # Type
    64547f99-7471-496a-8b02-5d48e09a72f9: 'Social Media' # Social Media
    78023dfa-3c9e-47d1-bedc-b6fa76c9d751: 'Teaser Image Placeholder' # Teaser Image Placeholder
    085923fe-5934-4d01-a2fd-ec625094c005: Caption # Caption
    97956e7f-3294-43b2-9d6a-e717706432bc: 'Optimize Articles' # Optimize Articles
    00439342-c87c-426d-8370-a874a8837d7c: 'Hero Image' # Hero Image
    815594b4-d88f-4430-bf0c-5db890e1051f: 'Profile Photo' # Profile Photo
    6180741d-7a95-4c38-a6b8-13f0cd8dab1f: 'Logo Icon' # Logo Icon
    12311739-6ceb-4fb4-a572-7f2ea0ad3b69: Documents # Documents
    76099428-f3d4-42a7-9bb8-08f425b41461: 'Organisation Name' # Organisation Name
    98769057-9c93-4e96-89ff-cb7b6a3a1188: 'Secondary Navigation' # Secondary Navigation
    a2aa1ca5-9822-4918-9c36-9b612669921b: Placeholders # Placeholders
    a5cb77be-c4d9-4d3e-88fb-d5384ca13941: 'Error Image' # Error Image
    a9df6c46-5d2c-4b29-96f7-4490417448b6: 'The Question' # The Question
    a72bfe0c-3389-4f9f-8ec1-ab318ec10b29: Errors # Errors
    aa00fbfa-4274-4def-a5e0-651e06d5baae: Button # Button
    af937c7b-a59e-445e-ac72-b9c36b9854f0: Buttons # Buttons
    b011a3f9-88a2-4819-aad0-ca04487dfac8: Documents # Documents
    b06ee5f5-05a5-4b2d-ae59-122bff896ee6: Standfirst # Standfirst
    b5a93f0f-21d1-4d67-abc8-a3789543d457: Image # Image
    b8ba7115-3804-4c06-8a96-501963d1fc5c: 'Error Headline' # Error Headline
    b51f4d5a-4d35-43f1-af05-72e206874892: 'Footer Navigation' # Footer Navigation
    b2330e68-6c4a-45ab-b5b1-8a510f75ce4f: General # General
    bbb59518-7cdc-4a7f-b07c-cd6b1fa8201d: Users # Users
    bed154da-9840-46ef-9810-0605c1307746: 'Spotlight Cards' # Spotlight Cards
    c014f72e-6101-4377-a9e4-bbea0f16bce8: Placeholders # Placeholders
    c157a704-5673-46ee-8e9b-49dfba9d3d5f: 'Hero Image Placeholder' # Hero Image Placeholder
    c439e251-a130-434d-a716-aab4d0651420: 'Navigation Settings' # Navigation Settings
    cc4d5589-5884-4fb2-ba84-ffb388a8806e: Slides # Slides
    d08a0d16-0e00-49e6-9cd4-465fa2d65d7d: Errors # Errors
    d08d0466-34f4-441b-acd1-439b514f3810: 'Profile Photo Placeholder' # Profile Photo Placeholder
    d7c71eec-4319-4f22-8bc6-a8bf17da8f3d: 'News Categories' # News Categories
    d8cef538-a756-4496-b7f6-0e0bb61c14c2: 'Primary Navigation' # Primary Navigation
    d39b90d3-13a8-4d42-b415-1ef20426a174: 'Photo Cover Placeholder' # Photo Cover Placeholder
    d57e5f8e-8914-40a4-9743-1c213f66843a: Cards # Cards
    dbb9d34a-ed00-430b-a6cd-e61927f7b2d5: Articles # Articles
    dcdd5839-4bb5-4669-8d82-d46ec4da660a: 'Image Source' # Image Source
    de0ad924-50fa-43fc-9790-e44bf330cdd2: Quotation # Quotation
    df090dc9-1e25-4504-abd3-18e7996d8d6d: 'Article Image Placeholder' # Article Image Placeholder
    dffe2f47-18b7-4dcb-845d-2d88fa0378c3: 'Organisational Information' # Organisational Information
    e0ee7443-387e-4be3-a64f-3c5ae52be354: 'Organisation Email' # Organisation Email
    e0745046-9bad-4922-8da8-7f677ba84909: 'Legal Navigation' # Legal Navigation
    e2c376a5-8341-40da-993a-68704f00171e: 'Resource List' # Resource List
    e6d658aa-c335-4f15-bbcd-59fe05d9e913: 'Error Text' # Error Text
    e7b63d80-91cc-438a-b670-59cbb778ca14: Description # Description
    e7d483ec-b6b2-440d-8e97-ae6cc84d0adb: 'Optimize Heroes' # Optimize Heroes
    e691301b-7484-40be-a3d4-c3bc590de959: 'Content Builder' # Content Builder
    ea74ba6b-b787-414c-9f83-a01b8377bd73: Heading # Heading
    ec91bde6-778d-4030-89fe-45614d871e81: Target # Target
    ed4b0f49-8429-4d80-846f-3d441bd3e707: Image # Image
    ef841ba4-7bcd-4ef5-9c12-96377bf7fba2: Pages # Pages
    f1db3ebb-c604-4fa8-9f2d-4255e0515ea9: Buttons # Buttons
    f4cbe95b-c71a-42f8-a9d8-464dcf3916a9: 'Primary Navigation' # Primary Navigation
    f3960fae-d20a-4473-9a73-315dfed31760: Image # Image
    f89601e9-4ba9-4a48-9e99-350aa9914912: Default # Default
    f326369d-c220-40d9-92e9-7b7b7811d8e5: 'News Categories' # News Categories
    faceb3ed-6771-453c-9c2a-aa330847f6db: Errors # Errors
    fb3a8f31-d1cc-4c13-903b-a501f7e51f54: Homepage # Homepage
    fbaa4c75-7616-42ca-adea-7615c9b91e38: Label # Label
    fe7c86d0-397a-4931-b026-ec32fdb7933b: Limit # Limit
plugins:
  aws-s3:
    eager-beaver:
      enabled: true
      schemaVersion: 1.0.0
    enabled: true
    schemaVersion: '1.2'
  blitz-recommendations:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  eager-beaver:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  fastcgi-cache-bust:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    enabled: true
    schemaVersion: 4.4.0
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: 9E0GNZGDICQUC701CD805KLG
    schemaVersion: 1.0.0
    settings:
      allowUpScaledImageVariants: false
      assetVolumeSubFolders: true
      autoSharpenScaledImages: true
      createColorPalette: true
      createPlaceholderSilhouettes: false
      imageTransformTypeSettings:
        __assoc__:
          -
            - nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform
            -
              __assoc__:
                -
                  - domain
                  - ''
                -
                  - apiKey
                  - ''
                -
                  - securityToken
                  - ''
          -
            - nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - $SERVERLESS_SHARP_CLOUDFRONT_URL
          -
            - nystudio107\imageoptimizethumbor\imagetransforms\ThumborImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
                -
                  - securityKey
                  - ''
                -
                  - includeBucketPrefix
                  - ''
      lowerQualityRetinaImageVariants: false
      transformClass: nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: VZHHXH5F4GCNNAD7EOB2O4AX
    schemaVersion: 1.0.21
    settings:
      bypassProjectConfig: false
      pluginName: Navigation
  notifications:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  password-policy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  position-fieldtype:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    enabled: true
    schemaVersion: 2.3.0
  retour:
    edition: standard
    enabled: true
    licenseKey: ZE62VWFIEPM6EVJRS53A9MHO
    schemaVersion: 3.0.9
    settings:
      additionalHeaders: ''
      alwaysStripQueryString: true
      automaticallyTrimStatistics: '1'
      createUriChangeRedirects: true
      dynamicRedirectDisplayLimit: 100
      enableApiEndpoint: ''
      excludePatterns: ''
      pluginName: Redirects
      preserveQueryString: false
      recordRemoteIp: true
      refreshIntervalSecs: 5
      staticRedirectDisplayLimit: 100
      statisticsRateLimitMs: '3600000'
      statsDisplayLimit: 1000
      statsStoredLimit: 1000
      stripQueryStringFromStats: true
      uriChangeRedirectSrcMatch: pathonly
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 5YI6AYBOTC0YJ0K6RVK0J93W
    schemaVersion: 3.0.11
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: ''
      enableMetaContainerEndpoint: ''
      environment: $ENVIRONMENT
      generatorEnabled: true
      headersEnabled: true
      lowercaseCanonicalUrl: '1'
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 'null'
      pluginName: SEO
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
        - linkedin
        - slack
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
  spoon:
    edition: standard
    enabled: true
    licenseKey: 5ORYCU819DCEOPQB8B5ERU5N
    schemaVersion: 3.5.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  webperf:
    edition: standard
    enabled: true
    licenseKey: 6ZQLWJ6TZE7FF8BU5LXCVIGF
    schemaVersion: 1.0.1
  width-fieldtype:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: Craft
  schemaVersion: 3.7.8
  timeZone: Europe/London
